qerror: Delete unused QERR_PROPERTY_VALUE_BAD macro
Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>
---
Cc: Markus Armbruster <armbru@redhat.com>
Cc: qemu-devel@nongnu.org